[server]
fileWatcherType = "none"
folderWatchBlacklist = ["ui/__pycache__", "app/__pycache__", "storage/chroma", "storage/memory", ".git"]

[client]
showErrorDetails = "full"

[logger]
level = "debug"